main: majhrs16.ssw.main
version: 1.7.6
name: SSW
commands:
  SetSpawnsWorlds:
    description: "Para obtener informacion sobre uso, escriba: /ssw help"

  ssw:
    description: "Para obtener informacion sobre uso, escriba: /ssw help"

permissions:
  ssw.set:
    descriptions: Permite el cambio de la configuracion.
    default: op

  ssw.infoplayer.get:
    descriptions: Muestra informacion detallada de un jugador.
    default: op

  ssw.ConflictWorldName.show:
    descriptions: Muestra cuando hay un conflicto de nombre entre mundos.
    default: op

  ssw.ConflictGamemode.show:
    descriptions: Muestra cuando hay un conflicto de nombre para el gamemode.
    default: op